### PR TITLE
 #10 Upload docs & set up wrangler for vercel @agrover112 @gizmotronn

### PR DESCRIPTION
**Pull request by Gizmotronn**
Creating pr to reference #10

Docs should also be accessible in `main` branch (aka `master`) imo, we can autogenerate docs based on markdown files @Agrover112 inside the module/library

E.g. let's say you create a doc page in `/docs` branch called "Why bees can't fly" with the meta tag for `doc-tag` being `bees`

We can setup a script in `main` branch that when using module in ide, user can type `/fliscopt help bees` and will find the "intro" meta about the bees entry in the markdown file in `/docs` branch, as well as a link to view the documentation site

### CODE REVIEW

**Comment by Agrover112** [comment]
Why did you close this @Gizmotronn  did you mess up something?

**Comment by Gizmotronn** [comment]
@Agrover112 i created the pr mainly for reference for when I actually created that module, if you think it's a good idea, but this is by no means ready to merge directly into #main

**Comment by Agrover112** [comment]
> @Agrover112 i created the pr mainly for reference for when I actually created that module, if you think it's a good idea, but this is by no means ready to merge directly into #main

yea looked like it.

**Comment by Gizmotronn** [comment]
Yep new merge is coming

**Pull request closed without merging**
