### PR TITLE
fix(readme): Add graphic

### LINKED ISSUE #11: Add logo/graphic for repository
A repository logo/graphic is required for aesthetic purposes.

### PR DESCRIPTION
**Pull request by Anik-Bardhan**
Closes #11 
@Agrover112 I have added a graphic and a logo file in the project, and updated the readme file. I have referred to the above mentioned graphics. Please mention any suggestion or changes to the graphic/logo file. I will look into it and make the necessary changes.

### CODE REVIEW

**Comment by Agrover112** [comment]
@Anik-Bardhan  Reviewing wait!

**Comment by Agrover112** [comment]
Hey @Anik-Bardhan  Thanks for the logo design appreciated!
Maybe you could add it to an images/ folder?
Also rename fliscopt(1)/(2) to something Heursitic like
fliscopt_graphic.jpg, fliscopt_logo.png? And finally link that renamed file to README.md

**Comment by Anik-Bardhan** [comment]
@Agrover112 okay on it.

**Comment by Anik-Bardhan** [comment]
@Agrover112 is it alright now?

**Comment by Agrover112** [comment]
> @Agrover112 is it alright now?

Yup, done merging 
Don't forget to ⭐ the repo XD

**Pull request merged**
