### PR TITLE
ci: automated release

### LINKED ISSUE #29: Add versioning Github action
An releases.yaml action that bumps the version number based on Semantic Versioning. (also updated __init__).py version.

### PR DESCRIPTION
**Pull request by krishguptadev**
fixes #29

### CODE REVIEW

**Comment by Agrover112** [comment]
@krishguptadev  I need the __version__ to be updated as well automatically.

**Comment by krishguptadev** [comment]
wdym? What is the version in init?

**Comment by Agrover112** [comment]
> wdym? What is the version in init?

For Python packages we need to update version number in __init__ , I'm not sure this updates it!?

**Comment by krishguptadev** [comment]
> > wdym? What is the version in init?
> 
> For Python packages we need to update version number in **init** , I'm not sure this updates it!?

it doesn't update that... and can't do it

**Comment by Agrover112** [comment]
> > > wdym? What is the version in init?
> > 
> > 
> > For Python packages we need to update version number in **init** , I'm not sure this updates it!?
> 
> it doesn't update that... and can't do it

Hmm , looks like it. Then I guess we close the issue then sadly :(

**Pull request closed without merging**
